'use client'

import React from 'react'
import { useAuth } from '@/contexts/AuthContext'
import MatrixButton from '@/components/ui/MatrixButton'

interface SignalsLayoutProps {
  children: React.ReactNode
}

const SignalsLayout: React.FC<SignalsLayoutProps> = ({ children }) => {
  const { user, logout } = useAuth()

  const handleLogout = () => {
    logout()
  }

  return (
    <div className="min-h-screen bg-black text-matrix-green">
      {/* Matrix Navigation Header */}
      <header className="border-b border-matrix-green/20 bg-black/90 backdrop-blur-sm sticky top-0 z-20">
        <div className="px-6 py-4">
          <div className="flex items-center justify-between">
            {/* Logo */}
            <div className="flex items-center space-x-4">
              <h1 className="text-2xl font-mono font-bold matrix-glitch glow-matrix" data-text="AI CASH">
                AI CASH
              </h1>
              <div className="text-sm font-mono text-matrix-dim">
                / NEURAL_SIGNALS_v1.0
              </div>
            </div>

            {/* Navigation Links */}
            <nav className="hidden md:flex items-center space-x-6">
              <a
                href="/dashboard"
                className="font-mono text-sm px-3 py-2 border border-matrix-green/30 text-matrix-green hover:border-matrix-green hover:text-matrix-bright transition-all"
              >
                DASHBOARD
              </a>
              <a
                href="/signals"
                className="font-mono text-sm px-3 py-2 border border-matrix-green text-matrix-bright glow-matrix bg-matrix-green/10 transition-all"
              >
                SIGNALS
              </a>
              <a
                href="/trading"
                className="font-mono text-sm px-3 py-2 border border-matrix-green/30 text-matrix-green hover:border-matrix-green hover:text-matrix-bright transition-all"
              >
                TRADING
              </a>
              <a
                href="/portfolio"
                className="font-mono text-sm px-3 py-2 border border-matrix-green/30 text-matrix-green hover:border-matrix-green hover:text-matrix-bright transition-all"
              >
                PORTFOLIO
              </a>
            </nav>

            {/* User Info & Logout */}
            <div className="flex items-center space-x-4">
              <div className="text-sm font-mono text-right">
                <div className="text-matrix-bright">{user?.email}</div>
                <div className="text-matrix-dim text-xs">{user?.subscriptionTier || 'FREE'}</div>
              </div>
              <MatrixButton
                onClick={handleLogout}
                variant="danger"
                size="sm"
              >
                JACK OUT
              </MatrixButton>
            </div>
          </div>
        </div>
      </header>

      {/* Mobile Navigation */}
      <div className="md:hidden border-b border-matrix-green/20 px-4 py-2">
        <div className="flex space-x-2 overflow-x-auto">
          <a href="/dashboard" className="font-mono text-xs px-3 py-2 border border-matrix-green/30 text-matrix-green whitespace-nowrap">
            DASH
          </a>
          <a href="/signals" className="font-mono text-xs px-3 py-2 border border-matrix-green text-matrix-bright bg-matrix-green/10 whitespace-nowrap">
            SIGNALS
          </a>
          <a href="/trading" className="font-mono text-xs px-3 py-2 border border-matrix-green/30 text-matrix-green whitespace-nowrap">
            TRADE
          </a>
          <a href="/portfolio" className="font-mono text-xs px-3 py-2 border border-matrix-green/30 text-matrix-green whitespace-nowrap">
            PORTFOLIO
          </a>
        </div>
      </div>

      {/* Neural Signals Header */}
      <div className="border-b border-matrix-green/20 bg-matrix-green/5 px-6 py-4">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-2xl font-mono font-bold text-matrix-bright glow-matrix">
                NEURAL SIGNAL MATRIX
              </h2>
              <p className="font-mono text-sm text-matrix-dim mt-1">
                AI-powered trading signals generated by quantum analysis algorithms
              </p>
            </div>
            <div className="hidden md:block">
              <MatrixButton
                onClick={() => window.location.reload()}
                variant="outline"
                size="sm"
              >
                REFRESH_MATRIX
              </MatrixButton>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <main className="relative z-10 p-6">
        <div className="max-w-7xl mx-auto">
          {children}
        </div>
      </main>

      {/* Signal Status Bar */}
      <div className="fixed bottom-0 left-0 right-0 bg-black/90 border-t border-matrix-green/20 px-4 py-2 z-20">
        <div className="flex items-center justify-between text-xs font-mono">
          <div className="flex items-center space-x-4">
            <span className="text-matrix-bright">NEURAL_STATUS:</span>
            <span className="animate-pulse-matrix">SCANNING</span>
            <span className="text-matrix-dim">|</span>
            <span>AI_MODELS: ACTIVE</span>
          </div>
          <div className="flex items-center space-x-4">
            <span>MODULE: SIGNAL_GENERATOR</span>
            <span className="text-matrix-dim">|</span>
            <span className="animate-pulse-matrix">⚡ QUANTUM_ANALYSIS</span>
          </div>
        </div>
      </div>

      {/* Floating Action Button for Mobile */}
      <div className="fixed bottom-20 right-4 z-30 md:hidden">
        <MatrixButton
          onClick={() => window.location.reload()}
          size="sm"
          className="rounded-full w-12 h-12 p-0 shadow-lg shadow-matrix-green/20"
        >
          ⟲
        </MatrixButton>
      </div>
    </div>
  )
}

export default SignalsLayout